### create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-k8s-deployment
  labels:
    app: boot-k8s
spec:
  selector:
    matchLabels:
      app: boot-k8s
  replicas: 4
  template:
    metadata:
      labels:
        app: boot-k8s
    spec:
      containers:
        - name: boot-k8s-container
          image: boot-k8s:1.0.0
          ports:
            - containerPort: 7000
---
### create service
apiVersion: v1
kind: Service
metadata:
  name: boot-k8s-service
spec:
  type: NodePort
  selector:
    app: boot-k8s
  ports:
    - protocol: TCP
      ## 容器服务端口
      port: 7000
      targetPort: 7000
      ## 对外暴露接口，容器的7000映射到外部主机的31000，公网访问31000端口即可
      nodePort: 31000